<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Employee;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $users = [
            [
                'firstName' => 'Cyd Joan',
                'middleName' => 'O',
                'lastName' => 'Simbala',
                'position' => 'Supervising Administrative Officer (HRMO IV)',
                'status' => 'Permanent',
                'division_id' => 1,
                'username' => 'CSimbala',
                'password' => 'CSimbala',
                'role' => 'Division Chief',
            ],[
                'firstName' => 'Kimjo',
                'middleName' => 'G',
                'lastName' => 'Acob',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'Casual',
                'division_id' => 2,
                'username' => 'KAcob',
                'password' => 'KAcob',
                'role' => 'Staff',
            ],[
                'firstName' => 'Ocean Mhay',
                'middleName' => 'O',
                'lastName' => 'Alindada',
                'position' => 'Administrative Aide IV (Clerk II)',
                'status' => 'Casual',
                'division_id' => 2,
                'username' => 'OAlindada',
                'password' => 'OAlindada',
                'role' => 'Staff',
            ],[
                'firstName' => 'Christine Joy',
                'middleName' => 'C',
                'lastName' => 'Bartolome',
                'position' => 'Administrative Aide IV (Clerk II)',
                'status' => 'Permantent',
                'division_id' => 2,
                'username' => 'CBartolome',
                'password' => 'CBartolome',
                'role' => 'Staff',
            ],[
                'firstName' => 'Dolores Marinatha',
                'middleName' => 'T',
                'lastName' => 'Belaras',
                'position' => 'Administrative Officer IV (HRMO II)',
                'status' => 'Permantent',
                'division_id' => 2,
                'username' => 'DBelaras',
                'password' => 'DBelaras',
                'role' => 'Staff',
            ],[
                'firstName' => 'Renz Brainerd',
                'middleName' => 'R',
                'lastName' => 'Cachola',
                'position' => 'Administrative Officer IV (HRMO II)',
                'status' => 'Permantent',
                'division_id' => 4,
                'username' => 'RCachola',
                'password' => 'RCachola',
                'role' => 'Division Chief',
            ],[
                'firstName' => 'Marc Ervin',
                'middleName' => 'Q',
                'lastName' => 'Calimag',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'Casual',
                'division_id' => 4,
                'username' => 'MCalimag',
                'password' => 'MCalimag',
                'role' => 'Staff',
            ],[
                'firstName' => 'Rovielene',
                'middleName' => 'B',
                'lastName' => 'Daniel',
                'position' => 'Administrative Assistant II (Clerk IV)',
                'status' => 'Permanent',
                'division_id' => 4,
                'username' => 'RDaniel',
                'password' => 'RDaniel',
                'role' => 'Staff',
            ],[
                'firstName' => 'Gwendolyn Iva',
                'middleName' => 'L',
                'lastName' => 'Daway',
                'position' => 'Administrative Assistant II (HRM Assistant)',
                'status' => 'Permanent',
                'division_id' => 1,
                'username' => 'GDaway',
                'password' => 'GDaway',
                'role' => 'Staff',
            ],[
                'firstName' => 'Keempee Paul',
                'middleName' => 'L',
                'lastName' => 'Dimal',
                'position' => 'Administrative Assistant II (Data Controller II)',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'KDimal',
                'password' => 'KDimal',
                'role' => 'Staff',
            ],[
                'firstName' => 'Jessalyn May',
                'middleName' => 'T',
                'lastName' => 'Domingo',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'Casual',
                'division_id' => 2,
                'username' => 'JDomingo',
                'password' => 'JDomingo',
                'role' => 'Staff',
            ],[
                'firstName' => 'Jose Estephen John',
                'middleName' => 'P',
                'lastName' => 'Estrella',
                'position' => 'Administrative Aide III (Driver I)',
                'status' => 'Permanent',
                'division_id' => 3,
                'username' => 'JEstrella',
                'password' => 'JEstrella',
                'role' => 'Staff',
            ],[
                'firstName' => 'Rowena VI',
                'middleName' => 'V',
                'lastName' => 'Esteban',
                'position' => 'Administrative Officer V (HRMO III)',
                'status' => 'Permanent',
                'division_id' => 3,
                'username' => 'REsteban',
                'password' => 'REsteban',
                'role' => 'Division Chief',
            ],[
                'firstName' => 'Brigit',
                'middleName' => 'P',
                'lastName' => 'Gamboa',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'Casual',
                'division_id' => 2,
                'username' => 'BGamboa',
                'password' => 'BGamboa',
                'role' => 'Staff',
            ],[
                'firstName' => 'Ellen Carr',
                'middleName' => 'O',
                'lastName' => 'Garingan',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'COS',
                'division_id' => 1,
                'username' => 'EGaringan',
                'password' => 'EGaringan',
                'role' => 'Staff',
            ],[
                'firstName' => 'Carol',
                'middleName' => 'G',
                'lastName' => 'Guntalilib',
                'position' => 'Provincial Government Assistant Department Head',
                'status' => 'Permanent',
                'division_id' => null,
                'username' => 'CGuntalilib',
                'password' => 'CGuntalilib',
                'role' => 'Assistant Department Head',
            ],[
                'firstName' => 'Julius Geron',
                'middleName' => 'N',
                'lastName' => 'Iglesias',
                'position' => 'Administrative Officer IV (HRMO II)',
                'status' => 'Permanent',
                'division_id' => 4,
                'username' => 'JIglesias',
                'password' => 'JIglesias',
                'role' => 'Staff',
            ],[
                'firstName' => 'Alisha Ashleigh',
                'middleName' => 'LA',
                'lastName' => 'Corda',
                'position' => 'Administrative Officer IV (HRMO II)',
                'status' => 'Permanent',
                'division_id' => 1,
                'username' => 'ALaCorda',
                'password' => 'ALaCorda',
                'role' => 'Staff',
            ],[
                'firstName' => 'Jhienette Rose',
                'middleName' => 'Y',
                'lastName' => 'Magno',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'COS',
                'division_id' => 2,
                'username' => 'JMagno',
                'password' => 'JMagno',
                'role' => 'Staff',
            ],[
                'firstName' => 'Reimark',
                'middleName' => 'J',
                'lastName' => 'Malamug',
                'position' => 'Administrative Assistant II (HRM Assistant)',
                'status' => 'Permanent',
                'division_id' => 1,
                'username' => 'RMalamug',
                'password' => 'RMalamug',
                'role' => 'Staff',
            ],[
                'firstName' => 'Marielle Bernadette',
                'middleName' => 'G',
                'lastName' => 'Manaig',
                'position' => 'Administrative Assistant II (HRM Assistant)',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'MManaig',
                'password' => 'MManaig',
                'role' => 'Staff',
            ],[
                'firstName' => 'Donalyn',
                'middleName' => 'T',
                'lastName' => 'Manghi',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'COS',
                'division_id' => 4,
                'username' => 'DManghi',
                'password' => 'DManghi',
                'role' => 'Staff',
            ],[
                'firstName' => 'Princess',
                'middleName' => 'A',
                'lastName' => 'Martinez',
                'position' => 'Administrative Aide IV (HRM Aide)',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'PMartinez',
                'password' => 'PMartinez',
                'role' => 'Staff',
            ],[
                'firstName' => 'Evangeline',
                'middleName' => 'D',
                'lastName' => 'Medina',
                'position' => 'Administrative Aide II (Messenger)',
                'status' => 'Permanent',
                'division_id' => 3,
                'username' => 'EMedina',
                'password' => 'EMedina',
                'role' => 'Staff',
            ],[
                'firstName' => 'Allen',
                'middleName' => 'E',
                'lastName' => 'Navarro',
                'position' => 'Administrative Officer V',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'ANavarro',
                'password' => 'ANavarro',
                'role' => 'Division Chief',
            ],[
                'firstName' => 'Jesus',
                'middleName' => 'D',
                'lastName' => 'Paladin Jr',
                'position' => 'Administrative Aide III (Driver I)',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'JPaladin',
                'password' => 'JPaladin',
                'role' => 'Staff',
            ],[
                'firstName' => 'Harbie',
                'middleName' => 'A',
                'lastName' => 'Panis',
                'position' => 'Administrative Aide III (Driver I)',
                'status' => 'Casual',
                'division_id' => 2,
                'username' => 'HPanis',
                'password' => 'HPanis',
                'role' => 'Staff',
            ],[
                'firstName' => 'Christian Dave',
                'middleName' => 'B',
                'lastName' => 'Pascua',
                'position' => 'Administrative Aide IV (HRM Aide)',
                'status' => 'Permanent',
                'division_id' => 3,
                'username' => 'CPascua',
                'password' => 'CPascua',
                'role' => 'Staff',
            ],[
                'firstName' => 'Anna Riza',
                'middleName' => 'A',
                'lastName' => 'Pumanes',
                'position' => 'Administrative Aide IV (HRM Aide)',
                'status' => 'Permanent',
                'division_id' => 2,
                'username' => 'APumanes',
                'password' => 'APumanes',
                'role' => 'Staff',
            ],[
                'firstName' => 'Janelle Marie',
                'middleName' => 'G',
                'lastName' => 'Reyes',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'COS',
                'division_id' => 3,
                'username' => 'JReyes',
                'password' => 'JReyes',
                'role' => 'Staff',
            ],[
                'firstName' => 'Saniata',
                'middleName' => 'A',
                'lastName' => 'Tarlit',
                'position' => 'Administrative Assistant II (HRM Assistant)',
                'status' => 'Permanent',
                'division_id' => 3,
                'username' => 'STarlit',
                'password' => 'STarlit',
                'role' => 'Staff',
            ],[
                'firstName' => 'Ma. Carla Lucia',
                'middleName' => 'M',
                'lastName' => 'Torralba',
                'position' => 'Provincial Human Resource Management Officer',
                'status' => 'Permanent',
                'division_id' => null,
                'username' => 'MTorralba',
                'password' => 'MTorralba',
                'role' => 'Department Head',
            ],[
                'firstName' => 'Rochelle',
                'middleName' => 'D',
                'lastName' => 'Torres',
                'position' => 'Administrative Aide IV (HRM Aide)',
                'status' => 'Permanent',
                'division_id' => 1,
                'username' => 'RTorres',
                'password' => 'RTorres',
                'role' => 'Staff',
            ],[
                'firstName' => 'Darlene Sarah',
                'middleName' => 'B',
                'lastName' => 'Licyayo',
                'position' => 'Administrative Aide III (Clerk I)',
                'status' => 'Casual',
                'division_id' => 3,
                'username' => 'DLicyayo',
                'password' => 'DLicyayo',
                'role' => 'Staff',
            ],
        ];

        foreach($users as $user) {
            Employee::create($user);
        }
    }
}

// Division_Id Basis
// Organizational Development Division = 1
// Appointments and Administrative Division = 2
// Personnel Relations and Discipline Division = 3
// Benefits and Welfare Division = 4
